builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    binary: "terraform-provider-lastpass_v{{ .Version }}"
archive:
  format: tar.gz
  files:
    - LICENSE
    - README.md
  format_overrides:
    - goos: windows
      format: zip
changelog:
  filters:
    exclude:
      - '^docs'
      - '^readme'
      - typo